version: '3.9'

services:
  db:
    image: postgres
    env_file:
      - ./buylando/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build:
      context: .
    command: >
      sh -c "python3 manage.py collectstatic --noinput &&
             python3 manage.py migrate &&
             python3 manage.py load_sample_users &&
             python3 manage.py load_sample_ecommerce_data &&
             gunicorn buylando.wsgi:application --bind 0.0.0.0:8000 --reload"
    expose:
      - 8000
    volumes:
      - .:/code
      - static:/code/static
      - media:/code/media
    depends_on:
      db:
        condition: service_healthy
  proxy:
    build:
      context: ./nginx
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static:/home/app/static
      - media:/home/app/media
    depends_on:
      web:
        condition: service_started
  mq:
    image: rabbitmq
  worker:
    build:
      context: .
    command: celery -A buylando worker -l INFO
    volumes:
      - .:/code
    depends_on:
      mq: 
        condition: service_started
      db:
        condition: service_healthy

volumes:
  static:
  media: