# Generated by Django 4.2 on 2023-04-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('C', 'Customer'), ('S', 'Seller')], default='C', max_length=1),
        ),
    ]
